//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympiad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Id { get; set; }
        public Nullable<int> PlaneId { get; set; }
        public Nullable<int> SrcId { get; set; }
        public Nullable<int> DestId { get; set; }
        public Nullable<System.DateTime> DateTakeOff { get; set; }
        public Nullable<System.DateTime> DateLanding { get; set; }
        public string Name { get; set; }
    
        public virtual AirPlane AirPlane { get; set; }
        public virtual AirPlane AirPlane1 { get; set; }
    }
}
