//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympiad
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_planeMoreInfo
    {
        public int id { get; set; }
        public Nullable<int> idp { get; set; }
        public string pic { get; set; }
        public Nullable<int> year { get; set; }
        public string Serial { get; set; }
    }
}
