//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympiad
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_companyPic
    {
        public int id { get; set; }
        public Nullable<int> idc { get; set; }
        public string pic { get; set; }
    }
}
