//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympiad
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Pilot
    {
        public int p_id { get; set; }
        public string p_FullName { get; set; }
        public Nullable<int> p_Passport { get; set; }
        public Nullable<int> p_Recruitment { get; set; }
        public Nullable<System.DateTime> p_BirthDate { get; set; }
        public string p_email { get; set; }
        public Nullable<int> p_RoleId { get; set; }
        public string p_pic { get; set; }
    
        public virtual tbl_Role tbl_Role { get; set; }
    }
}
