//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympiad
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_log
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> login { get; set; }
        public Nullable<System.DateTime> logout { get; set; }
    }
}
