//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympiad
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Username { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
